ContactAppRoleBasedLogin/Controllers/SignInController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ContactAppRoleBasedLogin.Data;
using ContactAppRoleBasedLogin.Models;
using System.Web.Security;
using ContactAppRoleBasedLogin.ViewModels;

namespace ContactAppRoleBasedLogin.Controllers
{
    public class SignInController : Controller
    {
        // GET: SignIn
        [AllowAnonymous]
        public ActionResult Login()
        {
            return View();
        }
        [AllowAnonymous]
        [HttpPost]
        public ActionResult Login(LoginVM loginVM)
        {
            if (!ModelState.IsValid)
            {
                return View(loginVM);
            }
            using (var session = NHibernateHelper.CreateSession())
            {
                using (var transaction = session.BeginTransaction())
                {
                    var findUser = session.Query<User>().SingleOrDefault(u => u.UserName == loginVM.UserName);
                    if (findUser != null)
                    {
                        if (findUser.IsActive)
                        {
                            if (BCrypt.Net.BCrypt.Verify(loginVM.Password, findUser.Password))
                            {
                                FormsAuthentication.SetAuthCookie(loginVM.UserName, true);
                                Session["UserId"] = findUser.Id;
                                if (findUser.IsAdmin)
                                {
                                    return RedirectToAction("ViewAllStaff", "User");

                                }
                                else
                                {
                                    return RedirectToAction("Index", "Contact");
                                }
                            }
                        }
                    }
                    ModelState.AddModelError("", "UserName/Password doesn't exists");
                    return View();
                }
            }
        }

        [Authorize(Roles = "Admin,Staff")]
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Login");
        }
    }
}

ContactAppRoleBasedLogin/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ContactAppRoleBasedLogin.Data;
using System.Web.Security;
using ContactAppRoleBasedLogin.Models;
using NHibernate.Linq;

namespace ContactAppRoleBasedLogin.Controllers
{
    /*
     ALTER TABLE Users
ADD CONSTRAINT DF_Users_Id DEFAULT NEWID() FOR Id
ALTER TABLE Contacts
ADD CONSTRAINT DF_Contacts_Id DEFAULT NEWID() FOR Id
ALTER TABLE ContactDetails
ADD CONSTRAINT DF_ContactDetails_Id DEFAULT NEWID() FOR Id
ALTER TABLE Roles
ADD CONSTRAINT DF_Roles_Id DEFAULT NEWID() FOR Id*/
    [Authorize(Roles = "Admin")]
    public class UserController : Controller
    {
        public ActionResult ViewAllStaff()
        {
            using (var session = NHibernateHelper.CreateSession())
            {
                var staffs = session.Query<User>().Where(u => u.IsAdmin == false).ToList();
                return View(staffs);
            }
        }
        public ActionResult ViewStaffContacts(Guid userId)
        {
            using(var session = NHibernateHelper.CreateSession())
            {
                var contacts = session.Query<Contact>().Where(c=>c.User.Id == userId).ToList();
                return View(contacts);
            }
        }
        public ActionResult ViewStaffContactDetails(Guid contactId)
        {
            using (var session = NHibernateHelper.CreateSession())
            {
                var contactDetails = session.Query<ContactDetail>().Where(cd=>cd.Contact.Id == contactId).ToList();
                return View(contactDetails);
            }
        }
        public ActionResult ViewAllAdmins()
        {
            using (var session = NHibernateHelper.CreateSession())
            {
                var admins = session.Query<User>().Where(u => u.IsAdmin == true).ToList();
                return View(admins);
            }
        }
        public ActionResult CreateUser()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CreateUser(User user)
        {
            if (!ModelState.IsValid)
            {
                return View(user);
            }
            user.Password= BCrypt.Net.BCrypt.HashPassword(user.Password);
            using (var session = NHibernateHelper.CreateSession())
            {
                using (var transaction = session.BeginTransaction())
                {
                    user.Role.User = user;
                    user.IsActive = true;
                    if (user.IsAdmin)
                    {
                        user.Role.RoleName = "Admin";
                    }
                    else
                    {
                        user.Role.RoleName = "Staff";
                    }
                    session.Save(user);
                    transaction.Commit();
                    return RedirectToAction("ViewAllStaff");
                }
            }
        }
        public ActionResult EditUser(Guid userId)
        {
            using (var session = NHibernateHelper.CreateSession())
            {
                var findUser = session.Get<User>(userId);
                return View(findUser);
            }
        }
        [HttpPost]

        public ActionResult EditUser(User user)
        {
            if (!ModelState.IsValid)
            {
                return View(user);
            }
            using (var session = NHibernateHelper.CreateSession())
            {
                using(var transaction = session.BeginTransaction())
                {
                    user.Role.User = user;
                    session.Update(user);
                    transaction.Commit();
                    if (user.IsAdmin)
                    {
                        return RedirectToAction("ViewAllAdmins");
                    }
                    return RedirectToAction("ViewAllStaff");
                }
            }
        }
        [HttpPost]
        public ActionResult ToggleIsActive(Guid userId, bool isActive)
        {
            using (var session = NHibernateHelper.CreateSession())
            {
                using (var transaction = session.BeginTransaction())
                {
                    var user = session.Get<User>(userId);
                    if (user != null)
                    {
                        user.IsActive = isActive;
                        session.Update(user);
                        transaction.Commit();
                    }
                }
            }

            return Json(new { success = true });
        }

    }
}

ContactAppRoleBasedLogin/Views/Shared/_AddContactPartial.cshtml
@model ContactAppRoleBasedLogin.Models.Contact

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Contact</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control my-3", id="fname"} })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control my-3", id = "lname" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="button" value="Create Contact" class="btn btn-outline-dark my-3" id="btnCreateContact" onclick="addNewContact()" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to Contact List", "Index", null, new { @class = "btn btn-outline-dark my-3" })
</div>

ContactAppRoleBasedLogin/Views/Shared/_EditContactPartial.cshtml
@model ContactAppRoleBasedLogin.Models.Contact

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Contact</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id, new {id="contactId"})

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control", id="editedFname" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control", id = "editedLname" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" value="Save" class="btn btn-outline-dark my-3" id="btnEdit" onclick="modifyContact()"/>
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to Contact List", "Index", null, new { @class = "btn btn-outline-dark my-3" })
</div>
@*<script>
    $("#btnEdit").click(() => {
        var data = {
            Id: $("#contactId").val(),
            FirstName:$("#editedFname").val(),
            LastName:$("#editedLname").val()
        }
        modifyContact(data)
    })
</script>*@

ContactAppRoleBasedLogin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>

    <!--styling links-->
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/bootstrap.min.js"></script>
    <link href="~/Content/jquery.jqGrid/ui.jqgrid.css" rel="stylesheet" />

    <!--first jquery then jqgrid-->
    <script src="~/Scripts/jquery-3.7.1.min.js"></script>
    <script src="~/Scripts/i18n/grid.locale-en.js"></script>
    <script src="~/Scripts/jquery.jqGrid.min.js"></script>
</head>
<body>
    <div class="navbar navbar-dark bg-dark navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("ContactApp", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                @if (User.Identity.IsAuthenticated)
                {
                    if (User.IsInRole("Admin"))
                    {
                        <span class="navbar-brand" style="color:white;">Welcome Admin </span>
                        @Html.ActionLink("Create New User", "CreateUser", "User", new { area = "" }, new { @class = "navbar-brand" })
                        @Html.ActionLink("View Admins", "ViewAllAdmins", "User", new { area = "" }, new { @class = "navbar-brand" })
                    }
                    else if (User.IsInRole("Staff"))
                    {
                        <span class="navbar-brand" style="color:white;">Welcome Staff </span>
                    }
                    @Html.ActionLink("Logout", "Logout", "SignIn", new { area = "" }, new { @class = "navbar-brand" })
                }
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
</body>
</html>